"""
engine/governor/email_guard.py

Lightweight quality gate for generated outreach emails.

Assessments go through a 4-guard Governor pipeline (confidence, summary
quality, evidence, opportunity-signal explainability) before being stored.
Email generation had *no* equivalent gate at all — complete_json() only
checked that "subject"/"body" were non-empty strings, so a well-formed but
generic, cliche-ridden, or unrelated-to-the-company email would sail through
untouched. This module is that missing gate for the email path specifically.

Not wired into engine/governor/guards.py's GUARD_PIPELINE because emails
are a different object shape (subject/body strings, not an enrichment dict)
generated by a separate LLM call at a different point in the flow — kept as
a standalone, purpose-built check instead of forcing it into that pipeline.
"""
from __future__ import annotations

import re
from typing import Any

MIN_WORDS = 25
MAX_WORDS = 180  # system prompt asks for <150; allow some slack before flagging

BANNED_PHRASES = [
    "i hope this finds you well", "i hope this email finds you",
    "reach out", "circle back", "touch base", "synergy", "synergies",
    "at your earliest convenience", "in today's fast-paced",
    "i wanted to reach out", "i wanted to connect", "leverage our",
    "game-changer", "game changer", "cutting-edge", "state-of-the-art",
    "streamline your operations", "take it to the next level",
]

COMPETITOR_NAMES = [
    "stripe", "gocardless", "xero", "quickbooks", "sage", "adyen",
    "checkout.com", "worldpay", "sumup", "square", "revolut business",
]

PLACEHOLDER_MARKERS = [
    "[company name]", "[name]", "[recipient", "{{", "}}", "dear sir/madam",
    "dear sir or madam", "to whom it may concern",
]

# Generic "what PayBrix does" boilerplate that keeps showing up verbatim
# across different companies' emails — the exact failure mode this guard
# exists to catch. If the model reaches for one of these fixed descriptions
# instead of grounding paragraph 2 in the specific firm, flag it.
GENERIC_PITCH_PATTERNS = [
    r"paybrix automates premium collection and reconciliation for irish insurance intermediaries",
    r"paybrix (is|helps) .{0,40}(automat|streamlin|simplif)",
]

_STOPWORDS = {
    "about", "after", "again", "against", "their", "there", "these", "those",
    "which", "would", "could", "should", "email", "brian", "paybrix",
    "insurance", "company", "irish", "firm", "years", "would", "your",
    "with", "have", "this", "that", "from", "been", "were", "being",
}


def _word_count(body: str) -> int:
    return len(re.findall(r"[A-Za-z']+", body))


def _significant_words(text: str, min_len: int = 5) -> set[str]:
    words = re.findall(r"[A-Za-z]+", (text or "").lower())
    return {w for w in words if len(w) >= min_len and w not in _STOPWORDS}


def evaluate_email(
    subject: str,
    body: str,
    grounding_text: str = "",
) -> dict[str, Any]:
    """
    Check a generated email for the specific failure modes that make
    outreach emails generic/repetitive despite a capable underlying model:
    formulaic clichés, a fixed company-agnostic product-pitch sentence,
    placeholder text, and zero lexical overlap with anything actually
    known about the recipient firm.

    Returns {"passed": bool, "issues": [str, ...], "word_count": int}.
    `passed=False` does not mean "discard" — the caller decides whether to
    retry, but the issues are always surfaced rather than silently dropped.
    """
    issues: list[str] = []
    body_lower = (body or "").lower()
    subject_lower = (subject or "").lower()

    wc = _word_count(body or "")
    if wc < MIN_WORDS:
        issues.append(f"body too short ({wc} words) — likely degenerate output")
    elif wc > MAX_WORDS:
        issues.append(f"body too long ({wc} words, target <150)")

    for phrase in BANNED_PHRASES:
        if phrase in body_lower or phrase in subject_lower:
            issues.append(f"contains banned cliche phrase: '{phrase}'")

    for name in COMPETITOR_NAMES:
        if name in body_lower:
            issues.append(f"names a competitor product: '{name}'")

    for marker in PLACEHOLDER_MARKERS:
        if marker in body_lower or marker in subject_lower:
            issues.append(f"contains unfilled placeholder text: '{marker}'")

    for pattern in GENERIC_PITCH_PATTERNS:
        if re.search(pattern, body_lower):
            issues.append("paragraph 2 reads like a fixed, company-agnostic PayBrix description")
            break

    # Grounding check: does the email actually reference anything specific
    # to this company (from opening_angle / company_context / verified
    # facts), or could it have been sent to any firm on the list?
    if grounding_text:
        grounding_words = _significant_words(grounding_text)
        body_words = _significant_words(body or "")
        overlap = grounding_words & body_words
        if grounding_words and len(overlap) == 0:
            issues.append("no lexical overlap with known company-specific facts — email may be generic")

    return {"passed": len(issues) == 0, "issues": issues, "word_count": wc}
